{
 "title": "Loki Gateway Metrics",
 "description": "The access-log-exporter dashboard provides real-time visualization and analysis of web server access logs collected via syslog. It displays key HTTP metrics such as request rates, response times, status codes, and data transfer volumes, supporting both Nginx and Apache servers. The dashboard enables users to monitor traffic patterns, detect anomalies, and gain insights into application performance and reliability, making it ideal for operational monitoring and troubleshooting. Metrics are customizable through presets, allowing tailored views for different monitoring needs.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(access_log_exporter_build_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(access_log_exporter_build_info{cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(access_log_exporter_build_info{cluster=~\"$cluster\", namespace=~\"$namespace\"},pod)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(access_log_exporter_build_info{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"},instance)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(http_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"},host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests ($__interval)",
   "type": "stat",
   "description": "The number of HTTP requests made in the last 1 minute window",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "% Success (period)",
   "type": "stat",
   "description": "This is the percentage of successful requests over the last minute.\n\nNOTE: Ignoring 404s in this metric, since a  404 is a normal response for errant requests",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",status=~\"[123]..\"}[${__range_s}s])) / \n(sum(rate(http_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\"}[${__range_s}s])))"
    }
   ]
  },
  {
   "title": "Connections (period)",
   "type": "stat",
   "description": "This is the number of connections handled.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_connections_accepted_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Req. not completed (period)",
   "type": "stat",
   "description": "Number of request that have been not completed.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(http_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\"}[${__range_s}s])) - sum(increase(http_requests_completed_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\"}[${__range_s}s]))>=0) or vector(0)",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "HTTP 1/2xx ($__interval)",
   "type": "stat",
   "description": "This is the number of successful requests in the last minute.  Successful being 1xx or 2xx by the standard HTTP definition.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",status=~\"[12]..\"}[$__interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "HTTP 3xx (period)",
   "type": "stat",
   "description": "This is the number of 3xx requests in the last minute.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",status=~\"3..\"}[${__range_s}s])) or vector(0)"
    }
   ]
  },
  {
   "title": "HTTP 4xx (period)",
   "type": "stat",
   "description": "This is the number of 4xx requests in the last minute.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",status=~\"4..\"}[${__range_s}s])) or vector(0)"
    }
   ]
  },
  {
   "title": "HTTP 5xx (period)",
   "type": "stat",
   "description": "This is the number of 5xx requests in the last minute.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",status=~\"5..\"}[${__range_s}s])) or vector(0)"
    }
   ]
  },
  {
   "title": "Requests (period)",
   "type": "stat",
   "description": "This is the total number of requests made in this period (top-right period selected)",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\"}[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "% Success ($__interval)",
   "type": "stat",
   "description": "This is the percentage of successful requests over the last minute.\n\nNOTE: Ignoring 404s in this metric, since a  404 is a normal response for errant requests",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",status=~\"[123]..\"}[$__interval])) / \n(sum(rate(http_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\"}[$__interval])))"
    }
   ]
  },
  {
   "title": "Connections ($__interval)",
   "type": "stat",
   "description": "This is the number of connections handled.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_connections_accepted_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Req. not completed ($__interval)",
   "type": "stat",
   "description": "Number of request that have been not completed.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(http_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\"}[$__interval])) - sum(increase(http_requests_completed_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\"}[$__interval]))>=0) or vector(0)",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "HTTP 1/2xx (period)",
   "type": "stat",
   "description": "This is the number of successful requests in the last minute.  Successful being 1xx or 2xx by the standard HTTP definition.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",status=~\"[12]..\"}[${__range_s}s])) or vector(0)"
    }
   ]
  },
  {
   "title": "HTTP 3xx ($__interval)",
   "type": "stat",
   "description": "This is the number of 3xx requests in the last minute.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",status=~\"3..\"}[$__interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "HTTP 4xx ($__interval)",
   "type": "stat",
   "description": "This is the number of 4xx requests in the last minute.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",status=~\"4..\"}[$__interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "HTTP 5xx ($__interval)",
   "type": "stat",
   "description": "This is the number of 5xx requests in the last minute.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",status=~\"5..\"}[$__interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "HTTP Requests / Host",
   "type": "timeseries",
   "description": "This is a total number of requests broken down by the host.  This can help get a sense of scale in relation to each other.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\"}[$__interval])) by (host)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "heatmap",
   "description": "The breakdown of the various HTTP status codes of the requests handled within' this period that matches the variables chosen above.\n\nThis chart helps notice and dive into which service is having failures and of what kind.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\"}[$__interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "description": "The total number of HTTP requests made within' each period",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\"}[$__interval]))",
     "legendFormat": "requests"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Latency (Average Percentiles)",
   "type": "timeseries",
   "description": "This graph can help assess and help us meet SLA requirements as far as the responsive time of our services.\n\nFor a more detailed latency graph broken out by ingress please open the closed tab at the bottom because it is very CPU intensive.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      http_request_duration_seconds_bucket{\n        cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",\n        status!=\"404|500|304|499\",\n      }[$__interval]\n    )\n  )\n)",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n      http_request_duration_seconds_bucket{\n        cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",\n        status!=\"404|500|304|499\",\n      }[$__interval]\n    )\n  )\n)",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (le)(\n    rate(\n      http_request_duration_seconds_bucket{\n        cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",\n        status!=\"404|500|304|499\",\n      }[$__interval]\n    )\n  )\n)",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le)(\n    rate(\n      http_request_duration_seconds_bucket{\n        cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",\n        status!=\"404|500|304|499\",\n      }[$__interval]\n    )\n  )\n)",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(\n  0.75,\n  sum by (le)(\n    rate(\n      http_request_duration_seconds_bucket{\n        cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",\n        status!=\"404|500|304|499\",\n      }[$__interval]\n    )\n  )\n)",
     "legendFormat": "0.75"
    },
    {
     "expr": "(\n\n(sum(increase(http_request_duration_seconds_bucket{\n    cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",\n    status!=\"404|500|304|499\",\n    le=\"0.01\"\n}[$__interval]))\n* 0.01)\n\n+\n\n((sum(increase(http_request_duration_seconds_bucket{\n    cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",\n    status!=\"404|500|304|499\",\n    le=\"0.1\"\n}[$__interval]))\n-\nsum(increase(http_request_duration_seconds_bucket{\n    cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",\n    status!=\"404|500|304|499\",\n    le=\"0.01\"\n}[$__interval])))\n* 0.1)\n\n+\n\n((sum(increase(http_request_duration_seconds_bucket{\n    cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",\n    status!=\"404|500|304|499\",\n    le=\"1\"\n}[$__interval]))\n-\nsum(increase(http_request_duration_seconds_bucket{\n    cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",\n    status!=\"404|500|304|499\",\n    le=\"0.1\"\n}[$__interval])))\n* 1)\n\n+\n\n((sum(increase(http_request_duration_seconds_bucket{\n    cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",\n    status!=\"404|500|304|499\",\n    le=\"10\"\n}[$__interval]))\n-\nsum(increase(http_request_duration_seconds_bucket{\n    cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",\n    status!=\"404|500|304|499\",\n    le=\"1\"\n}[$__interval])))\n* 10 )\n\n+\n\n((sum(increase(http_request_duration_seconds_bucket{\n    cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",\n    status!=\"404|500|304|499\",\n    le=\"30\"\n}[$__interval]))\n-\nsum(increase(http_request_duration_seconds_bucket{\n    cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",\n    status!=\"404|500|304|499\",\n    le=\"10\"\n}[$__interval])))\n* 30 )\n\n+\n\n((sum(increase(http_request_duration_seconds_bucket{\n    cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",\n    status!=\"404|500|304|499\",\n    le=\"60\"\n}[$__interval]))\n-\nsum(increase(http_request_duration_seconds_bucket{\n    cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",\n    status!=\"404|500|304|499\",\n    le=\"30\"\n}[$__interval])))\n* 60 )\n\n+\n\n((sum(increase(http_request_duration_seconds_bucket{\n    cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",\n    status!=\"404|500|304|499\",\n    le=\"+Inf\"\n}[$__interval]))\n-\nsum(increase(http_request_duration_seconds_bucket{\n    cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",\n    status!=\"404|500|304|499\",\n    le=\"60\"\n}[$__interval])))\n* 120 )\n\n) / \n\nsum(increase(http_request_duration_seconds_bucket{\n    cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\",\n    status!=\"404|500|304|499\",\n    le=\"+Inf\"\n}[$__interval]))\n",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Latency Heatmap",
   "type": "heatmap",
   "description": "This graph can help assess and help us meet SLA requirements as far as the responsive time of our services.\n\nFor a more detailed latency graph broken out by ingress please open the closed tab at the bottom because it is very CPU intensive.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\"}[$__rate_interval])) by(le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Network I/O pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_size_bytes_sum{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(http_response_size_bytes_sum{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Request Size Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(http_request_size_bytes_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\"}[$__rate_interval])) by(le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Size Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(http_response_size_bytes_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\"}[$__rate_interval])) by(le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "NGINX Status",
   "type": "table",
   "description": "This panel indicates the current status of the NGINX server for the selected instance, showing whether it's up or down.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "nginx_up{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"} == 1",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Processed connections",
   "type": "timeseries",
   "description": "This panel tracks the number of processed connections for the selected instance, displaying both active and handled connections to monitor server activity.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_connections_accepted_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "accepted"
    },
    {
     "expr": "sum(irate(nginx_connections_handled_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "description": "This panel shows NGINX active connections for the selected instance, categorized as writing, waiting, reading, and total active.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(nginx_connections_active{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"})",
     "legendFormat": "active"
    },
    {
     "expr": "sum(nginx_connections_reading{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"})",
     "legendFormat": "reading"
    },
    {
     "expr": "sum(nginx_connections_waiting{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"})",
     "legendFormat": "waiting"
    },
    {
     "expr": "sum(nginx_connections_writing{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"})",
     "legendFormat": "writing"
    }
   ]
  },
  {
   "title": "Host ($host)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "repeat": "host",
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Requests / Host",
     "type": "timeseries",
     "description": "This is a total number of requests broken down by the host.  This can help get a sense of scale in relation to each other.",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(http_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",instance=~\"$instance\",host=~\"$host\"}[$__interval])) by (host, path)",
       "legendFormat": "{{path}}"
      }
     ]
    }
   ]
  }
 ]
}