releases:
  - name: traefik
    namespace: traefik
    chart: helm-charts/traefik
    labels:
      stack: traefik
    values:
      - values/traefik/common.yaml
      - values/traefik/routes.yaml
    missingFileHandler: Error
