apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - job.yaml
configMapGenerator:
  - name: demo-load-k6
    files:
      - script.js
    options:
      disableNameSuffixHash: true
